### PR TITLE
Using temporary directory for saving the livepatch file

### LINKED ISSUE #1: The client should not create directories relative to $PWD
In https://github.com/aliceinwire/elivepatch-client/blob/master/elivepatch_client/restful.py#L116 the client creates a temporary directory relative to the current directory. This may potentially crash the client due to `EPERM` etc and should be fixed to an absolute path or eliminated completely.

### PR DESCRIPTION
**Pull request by aliceinwire**
instead of saving the file to a unsafe parent directory, 
use temporary directory for saving the livepatch file.

closes #1

### CODE REVIEW

**Comment by prometheanfire** [comment]
Is the live patch dir safe as a tmpdir?  Can other processes change the patch/data at the temporary location?

**Comment by aliceinwire** [comment]
the livepatch temporary directory name is randomized and is destroyed after the usage.
https://docs.python.org/3.5/library/tempfile.html#tempfile.TemporaryDirectory

**Review by prometheanfire — CHANGES_REQUESTED** [review]
ok, uses mkdtemp, which is secure

one thing that's missing is cleaning up the directory after use.  See https://docs.python.org/3.5/library/tempfile.html#tempfile.mkdtemp

**Comment by aliceinwire** [comment]
tempfile.TemporaryDirectory(suffix='', prefix='tmp', dir=None)

This function creates a temporary directory using mkdtemp() (the supplied arguments are passed directly to the underlying function). The resulting object can be used as a context manager (see With Statement Context Managers). __On completion of the context (or destruction of the temporary directory object), the newly created temporary directory and all its contents are removed from the filesystem.__

**Comment by prometheanfire** [comment]
ah, missed that

**Review by prometheanfire — APPROVED** [review]

**Pull request merged**
